language: groovy
jdk:
  - oraclejdk7
branches:
  only:
    - master
    - /^[0-9.]+.*$/
script: ./gradlew clean build uploadArchives
env:
  global:
  - GIT_NAME="Brian Saville"
  - GIT_EMAIL="bksaville@gmail.com"
  # travis encrypt -a env.global 'MAVEN_CENTRAL_USERNAME=myusername'
  # travis encrypt -a env.global 'MAVEN_CENTRAL_PASSWORD=mypassword'
  # travis encrypt -a env.global 'GITHUB_TOKEN=token' # get the token from https://github.com/settings/applications
  - secure: dVM+jJNq6YB0o6Fw48aST6oZ7QusSoMoiUBD71/QOW679J1XIQHwaP2RYRqGY5b6A6ub6X7WaSkJ+d569BTL491S7buJxH0+OqSGrduxCxOIkc/9O9eX26WoZtnseKJy2SjclFJaomusLKtvTLrR3nz0SL2sMuAhkCqu0ksbk6o=